# Generated by Django 5.0.2 on 2024-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='RImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='recentimage')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
