# Generated by Django 5.0.2 on 2024-02-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rimage',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
    ]
