# Generated by Django 5.0.2 on 2024-02-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
