# Generated by Django 5.0.2 on 2024-03-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_rimage_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Events',
        ),
    ]
