# Generated by Django 5.0.2 on 2024-03-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
