# Generated by Django 5.0.2 on 2024-03-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_events_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RImage',
            new_name='REvent',
        ),
    ]
