# Generated by Django 5.0.2 on 2024-03-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_rimage_revent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REvent',
            new_name='RImage',
        ),
    ]
