# Generated by Django 5.0.2 on 2024-03-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_revent_rimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RImage',
            new_name='RecentEvent',
        ),
    ]
