# Generated by Django 5.0.2 on 2024-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_rimage_recentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
